Metrics/LineLength:
  Max: 200

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false
